# Proyecto Sumativa 1 – Ciencia de Datos e IA

## Fase 1: Definición del proyecto y configuración del entorno

**Proyecto:** Análisis de generación y excedentes energéticos en plantas de celulosa CMPC  

**Integrantes:** Verónica Durán Cisterna, Raúl Moya Arriagada, Daniela Rojas, Manuel Sánchez

**Asignatura:** Programación para la Ciencia de Datos  

**Fecha: 16 de septiembre de 2026

## 1. Definición de la problemática

Las plantas de celulosa Santa Fe, Pacífico y Laja de CMPC cuentan con sistemas de cogeneración que producen energía eléctrica mediante turbogeneradores, permitiendo abastecer parte de los consumos internos de sus procesos productivos y generar excedentes de energía que pueden ser entregados al Sistema Eléctrico Nacional (CEN).

La generación y los excedentes presentan variaciones en el tiempo debido al comportamiento de los turbogeneradores y a los requerimientos energéticos propios de cada planta. Sin embargo, los registros operacionales disponibles no permiten por sí solos visualizar de manera consolidada estos comportamientos ni identificar fácilmente patrones, variaciones o períodos relevantes.

Para abordar esta problemática se dispone de un dataset con registros horarios de 2026 correspondientes a la generación de los turbogeneradores y variables asociadas a la autoproducción o excedentes energéticos de las instalaciones.

A partir de estos datos se propone desarrollar un análisis reproducible que permita caracterizar el comportamiento energético de las plantas, estudiar la relación entre generación, consumo interno y excedentes, e identificar patrones y desviaciones relevantes que puedan aportar información para la toma de decisiones.

## 2. Preguntas centrales

A partir de la problemática definida, el proyecto busca responder las siguientes preguntas:

1. ¿Cómo se comporta la generación eléctrica de los turbogeneradores de las plantas Santa Fe, Pacífico y Laja durante el período analizado?

2. ¿Qué patrones temporales se observan en la generación y en los excedentes energéticos de cada planta?

3. ¿Es posible estimar el consumo interno de las plantas a partir de la generación total y las variables de autoproducción (AP) disponibles?

4. ¿Existen períodos con variaciones o comportamientos atípicos que permitan identificar cambios relevantes en la operación energética de las plantas?

5. ¿Qué diferencias se observan en el comportamiento energético entre las plantas Santa Fe, Pacífico y Laja?

## 3. Objetivo general

Analizar el comportamiento energético de las plantas de celulosa Santa Fe, Pacífico y Laja de CMPC, a partir de registros horarios de generación eléctrica y autoproducción correspondientes al año 2026, con el propósito de caracterizar sus patrones operacionales, estimar el consumo interno e identificar variaciones relevantes en la generación y los excedentes de energía.

## 4. Objetivos específicos

1. Evaluar la calidad y estructura de los datos disponibles, identificando valores faltantes, duplicados, tipos de datos e inconsistencias que puedan afectar el análisis.

2. Analizar el comportamiento temporal de la generación eléctrica de los turbogeneradores de las plantas Santa Fe, Pacífico y Laja.

3. Caracterizar los excedentes energéticos registrados para cada planta e identificar sus variaciones a través del tiempo.

4. Estimar el consumo interno de las plantas a partir de las variables de generación y autoproducción disponibles, cuando la estructura y definición de los datos lo permitan.

5. Comparar el comportamiento energético entre las plantas e identificar patrones, diferencias y períodos con variaciones relevantes.

6. Generar indicadores y visualizaciones que faciliten la interpretación de los resultados obtenidos.

## 5. Alcance del proyecto

El proyecto considera el análisis de los registros energéticos disponibles para las plantas Santa Fe, Pacífico y Laja durante el período comprendido en el dataset del año 2026.

### Incluye

- Exploración y evaluación de la calidad de los datos.
- Análisis de la generación eléctrica registrada por los turbogeneradores.
- Análisis de las variables de autoproducción (AP) y excedentes energéticos.
- Análisis temporal a nivel horario y otras agrupaciones que resulten pertinentes.
- Estimación del consumo interno cuando las variables disponibles permitan realizar el cálculo.
- Comparación del comportamiento energético entre las plantas.
- Identificación de patrones, variaciones y posibles comportamientos atípicos.
- Elaboración de indicadores y visualizaciones para apoyar la interpretación de los datos.

### Excluye

- Modificaciones o intervenciones sobre la operación real de las plantas.
- Desarrollo de sistemas de control automático de los turbogeneradores.
- Predicciones o modelos de optimización que no puedan ser sustentados con los datos disponibles.
- Evaluaciones económicas que requieran información externa no disponible o cuya relación con las variables del dataset no pueda ser validada.

## 6. Supuestos relevantes

Para el desarrollo del proyecto se consideran inicialmente los siguientes supuestos:

- Los registros del dataset corresponden a mediciones horarias asociadas a la operación energética de las instalaciones durante el período informado.
- Las variables de los turbogeneradores representan potencia eléctrica expresada en MW. Para obtener energía en MWh se deberá considerar el intervalo temporal correspondiente.
- Las variables identificadas como AP se encuentran asociadas a la autoproducción o excedente energético de cada instalación, de acuerdo con las definiciones operacionales disponibles.
- La interpretación de valores positivos, negativos y cercanos a cero será validada antes de realizar transformaciones o cálculos derivados.
- La estimación del consumo interno se realizará únicamente cuando sea posible establecer y validar la relación entre generación y excedente energético.
- Los datos originales se mantendrán sin modificaciones y cualquier proceso de limpieza, transformación o cálculo será realizado mediante código reproducible.
- Los comportamientos atípicos no serán considerados automáticamente como errores, ya que pueden corresponder a condiciones reales de operación.

## 7. Articulación del proyecto con las fases F1–F4

El proyecto se desarrollará de manera progresiva a través de las siguientes fases:

- **F1 – Definición:** formulación de la problemática, preguntas centrales, objetivos, alcance, supuestos y configuración inicial del entorno reproducible.

- **F2 – Preparación y exploración de datos:** carga, exploración, limpieza, transformación y validación del dataset, manteniendo trazabilidad de los cambios realizados.

- **F3 – Análisis:** desarrollo de indicadores, análisis temporal, comparación entre plantas e identificación de patrones y comportamientos relevantes.

- **F4 – Resultados:** interpretación de los hallazgos, elaboración de conclusiones y presentación de los principales resultados del proyecto.

## 8. Configuración inicial del entorno reproducible

Para asegurar la reproducibilidad del proyecto se utiliza un entorno virtual de Python, en el cual se instalan y controlan las librerías necesarias para el desarrollo del análisis.

A continuación, se verifica la versión de Python y de las principales librerías utilizadas.]

In [16]:
import sys
import pandas as pd
import numpy as np
import matplotlib

print("CONFIGURACIÓN DEL ENTORNO")
print("-------------------------")
print(f"Python: {sys.version.split()[0]}")
print(f"Pandas: {pd.__version__}")
print(f"NumPy: {np.__version__}")
print(f"Matplotlib: {matplotlib.__version__}")

CONFIGURACIÓN DEL ENTORNO
-------------------------
Python: 3.14.3
Pandas: 3.0.5
NumPy: 2.5.3
Matplotlib: 3.11.1

In [17]:
sys.version

'3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)]'

In [18]:
pd.__version__
np.__version__
matplotlib.__version__

'3.11.1'

### 8.1 Ubicación del dataset

El dataset original se almacena dentro de la estructura del proyecto en la carpeta `data/raw`. Para evitar el uso de rutas absolutas asociadas a un computador específico, se utiliza `Path` para construir la ruta relativa al proyecto.

In [19]:
from pathlib import Path

ruta_proyecto = Path.cwd().parent
ruta_archivo = ruta_proyecto / "data" / "raw" / "dataset_proyecto_vf.csv"

print("Ruta del proyecto:")
print(ruta_proyecto)

print("\nRuta del dataset:")
print(ruta_archivo)

print("\n¿El archivo existe?")
print(ruta_archivo.exists())

Ruta del proyecto:
c:\Users\eliza\Desktop\ESTUDIOS\MAGÍSTER\1 PROGRAMACIÓN PARA LA CIENCIA\Proyecto

Ruta del dataset:
c:\Users\eliza\Desktop\ESTUDIOS\MAGÍSTER\1 PROGRAMACIÓN PARA LA CIENCIA\Proyecto\data\raw\dataset_proyecto_vf.csv

¿El archivo existe?
True

In [20]:
Path.cwd()

WindowsPath('c:/Users/eliza/Desktop/ESTUDIOS/MAGÍSTER/1 PROGRAMACIÓN PARA LA CIENCIA/Proyecto/F1')

In [21]:
Path.cwd().parent

WindowsPath('c:/Users/eliza/Desktop/ESTUDIOS/MAGÍSTER/1 PROGRAMACIÓN PARA LA CIENCIA/Proyecto')

In [22]:
ruta_proyecto / "data" / "raw" / "dataset_proyecto_vf.csv"

WindowsPath('c:/Users/eliza/Desktop/ESTUDIOS/MAGÍSTER/1 PROGRAMACIÓN PARA LA CIENCIA/Proyecto/data/raw/dataset_proyecto_vf.csv')

In [23]:
ruta_archivo.exists()

True

### 8.2 Carga inicial del dataset

El archivo se encuentra en formato CSV y utiliza punto y coma (`;`) como separador de columnas. Se realiza una carga inicial de los datos para verificar su correcta lectura y conocer sus dimensiones.

In [24]:
df = pd.read_csv(ruta_archivo, sep=";")

print("CARGA DEL DATASET")
print("-----------------")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

CARGA DEL DATASET
-----------------
Filas: 5833
Columnas: 17

### 8.3 Verificación de la estructura del dataset

Una vez cargado el archivo, se realiza una inspección inicial de su estructura para identificar las variables disponibles y visualizar una muestra de los registros. En esta etapa no se realizan modificaciones sobre los datos.

In [25]:
print("COLUMNAS DEL DATASET")
print("--------------------")

for columna in df.columns:
    print(columna)

print("\nPRIMEROS REGISTROS")
display(df.head())

COLUMNAS DEL DATASET
--------------------
Fecha
Dia_Semana
SANTA_FE_TG1
SANTA_FE_TG2
SANTA_FE_TG3
PACIFICO_TG1
PACIFICO_TG2
PACIFICO_TG3
LAJA_TG3
LAJA_TG4
SF _ENERGÍA_TG4
SF _ENERGÍA_(NETO)
LAJA AP
PACIFICO AP
SANTA FE AP
CMPC BUCALEMU_52EG
CMPC BUCALEMU 52ET

PRIMEROS REGISTROS

,Fecha,Dia_Semana,SANTA_FE_TG1,SANTA_FE_TG2,SANTA_FE_TG3,PACIFICO_TG1,PACIFICO_TG2,PACIFICO_TG3,LAJA_TG3,LAJA_TG4,SF _ENERGÍA_TG4,SF _ENERGÍA_(NETO),LAJA AP,PACIFICO AP,SANTA FE AP,CMPC BUCALEMU_52EG,CMPC BUCALEMU 52ET
0,01/01/2026 1:00,jueves,"-19,03","-44,57","-43,82","-29,98","-28,09","-9,54","-26,55","-19,95","-46,80","-40,86","-1,15","-20,05","-9,29","-5,24","-4,92"
1,01/01/2026 2:00,jueves,"-19,02","-44,63","-44,46","-30,04","-27,10","-9,58","-23,46","-33,91","-48,46","-42,36","-11,40","-19,39","-8,01","-5,49","-5,25"
2,01/01/2026 3:00,jueves,"-18,94","-44,61","-44,03","-30,02","-27,35","-9,48","-24,20","-32,18","-49,32","-43,19","-10,28","-19,05","-6,92","-5,44","-5,31"
3,01/01/2026 4:00,jueves,"-19,01","-44,71","-44,49","-32,05","-28,15","-9,56","-26,43","-26,41","-52,38","-45,91","-6,93","-21,55","-7,23","-4,64","-4,59"
4,01/01/2026 5:00,jueves,"-19,06","-44,69","-44,46","-32,10","-30,62","-9,56","-25,09","-29,58","-58,14","-51,60","-8,38","-24,05","-8,07","-4,91","-4,61"

### 8.4 Verificación de los tipos de datos

Se revisan los tipos de datos asignados inicialmente por Pandas a cada variable. Esta verificación permite identificar si las fechas y variables numéricas fueron interpretadas correctamente durante la carga del archivo.

In [26]:
print("TIPOS DE DATOS")
print("--------------")
print(df.dtypes)

TIPOS DE DATOS
--------------
Fecha                 str
Dia_Semana            str
SANTA_FE_TG1          str
SANTA_FE_TG2          str
SANTA_FE_TG3          str
PACIFICO_TG1          str
PACIFICO_TG2          str
PACIFICO_TG3          str
LAJA_TG3              str
LAJA_TG4              str
SF _ENERGÍA_TG4       str
SF _ENERGÍA_(NETO)    str
LAJA AP               str
PACIFICO AP           str
SANTA FE AP           str
CMPC BUCALEMU_52EG    str
CMPC BUCALEMU 52ET    str
dtype: object

### Hallazgo inicial sobre los tipos de datos

La inspección inicial muestra que las 17 variables fueron interpretadas como texto (`str`). Esto incluye tanto la variable `Fecha` como las columnas que contienen mediciones energéticas.

Por lo tanto, antes de realizar cálculos o análisis estadísticos será necesario convertir las variables a los tipos de datos apropiados. Esta transformación se realizará posteriormente de forma reproducible, manteniendo intacto el archivo original.

### 8.5 Verificación reproducible del dataset

Con el propósito de incorporar una primera estructura modular al proyecto, se define una función que permite verificar la existencia del archivo y realizar su carga de manera controlada. Esta función constituye una operación inicial de Fase 1 y podrá ser reutilizada en las etapas posteriores del proyecto.

In [29]:
def cargar_dataset(ruta, separador=";"):
    """
    Verifica la existencia del dataset y realiza su carga.

    Parámetros:
        ruta: ubicación del archivo.
        separador: carácter utilizado para separar las columnas.

    Retorna:
        DataFrame con los datos cargados.
    """
    
    if not ruta.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {ruta}")
    
    datos = pd.read_csv(ruta, sep=separador)
    
    print("Dataset cargado correctamente.")
    print(f"Filas: {datos.shape[0]}")
    print(f"Columnas: {datos.shape[1]}")
    
    return datos

In [30]:
df_prueba = cargar_dataset(ruta_archivo)

Dataset cargado correctamente.
Filas: 5833
Columnas: 17

In [31]:
df_prueba

,Fecha,Dia_Semana,SANTA_FE_TG1,SANTA_FE_TG2,SANTA_FE_TG3,PACIFICO_TG1,PACIFICO_TG2,PACIFICO_TG3,LAJA_TG3,LAJA_TG4,SF _ENERGÍA_TG4,SF _ENERGÍA_(NETO),LAJA AP,PACIFICO AP,SANTA FE AP,CMPC BUCALEMU_52EG,CMPC BUCALEMU 52ET
0,01/01/2026 1:00,jueves,"-19,03","-44,57","-43,82","-29,98","-28,09","-9,54","-26,55","-19,95","-46,80","-40,86","-1,15","-20,05","-9,29","-5,24","-4,92"
1,01/01/2026 2:00,jueves,"-19,02","-44,63","-44,46","-30,04","-27,10","-9,58","-23,46","-33,91","-48,46","-42,36","-11,40","-19,39","-8,01","-5,49","-5,25"
2,01/01/2026 3:00,jueves,"-18,94","-44,61","-44,03","-30,02","-27,35","-9,48","-24,20","-32,18","-49,32","-43,19","-10,28","-19,05","-6,92","-5,44","-5,31"
3,01/01/2026 4:00,jueves,"-19,01","-44,71","-44,49","-32,05","-28,15","-9,56","-26,43","-26,41","-52,38","-45,91","-6,93","-21,55","-7,23","-4,64","-4,59"
4,01/01/2026 5:00,jueves,"-19,06","-44,69","-44,46","-32,10","-30,62","-9,56","-25,09","-29,58","-58,14","-51,60","-8,38","-24,05","-8,07","-4,91","-4,61"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,31/08/2026 20:00,lunes,"-16,97","0,00","0,00","-35,83","-18,98","-8,66","0,00","-29,84","-32,32","-26,83","12,77","-16,89","43,84","-3,42","-2,43"
5829,31/08/2026 21:00,lunes,"-16,97","0,00","0,00","-35,78","-18,65","-8,66","0,00","-35,33","-33,47","-28,00","7,13","-17,08","43,67","-4,14","-3,13"
5830,31/08/2026 22:00,lunes,"-16,97","0,00","0,00","-36,08","-17,48","-8,67","0,00","-37,15","-30,50","-24,91","5,35","-16,43","44,67","-4,04","-3,14"
5831,31/08/2026 23:00,lunes,"-16,97","0,00","0,00","-35,59","-16,80","-8,67","0,00","-31,66","-40,40","-34,35","10,92","-14,99","45,89","-4,02","-3,13"
5832,01/09/2026 0:00,martes,"-16,97","0,00","0,00","-35,93","-13,18","-8,66","0,00","-34,31","-30,66","-25,08","7,84","-11,56","46,94","-3,28","-2,31"

In [32]:
df_prueba.head()

,Fecha,Dia_Semana,SANTA_FE_TG1,SANTA_FE_TG2,SANTA_FE_TG3,PACIFICO_TG1,PACIFICO_TG2,PACIFICO_TG3,LAJA_TG3,LAJA_TG4,SF _ENERGÍA_TG4,SF _ENERGÍA_(NETO),LAJA AP,PACIFICO AP,SANTA FE AP,CMPC BUCALEMU_52EG,CMPC BUCALEMU 52ET
0,01/01/2026 1:00,jueves,"-19,03","-44,57","-43,82","-29,98","-28,09","-9,54","-26,55","-19,95","-46,80","-40,86","-1,15","-20,05","-9,29","-5,24","-4,92"
1,01/01/2026 2:00,jueves,"-19,02","-44,63","-44,46","-30,04","-27,10","-9,58","-23,46","-33,91","-48,46","-42,36","-11,40","-19,39","-8,01","-5,49","-5,25"
2,01/01/2026 3:00,jueves,"-18,94","-44,61","-44,03","-30,02","-27,35","-9,48","-24,20","-32,18","-49,32","-43,19","-10,28","-19,05","-6,92","-5,44","-5,31"
3,01/01/2026 4:00,jueves,"-19,01","-44,71","-44,49","-32,05","-28,15","-9,56","-26,43","-26,41","-52,38","-45,91","-6,93","-21,55","-7,23","-4,64","-4,59"
4,01/01/2026 5:00,jueves,"-19,06","-44,69","-44,46","-32,10","-30,62","-9,56","-25,09","-29,58","-58,14","-51,60","-8,38","-24,05","-8,07","-4,91","-4,61"

### 8.6 Validación inicial de la carga

Se realizan verificaciones básicas para comprobar que el dataset fue cargado correctamente y que presenta la estructura esperada antes de continuar con las etapas posteriores del proyecto.

In [33]:
assert df_prueba.shape[0] > 0, "El dataset no contiene registros."
assert df_prueba.shape[1] == 17, "El número de columnas no corresponde al esperado."

print("Validación completada correctamente.")
print(f"Registros disponibles: {df_prueba.shape[0]}")
print(f"Variables disponibles: {df_prueba.shape[1]}")

Validación completada correctamente.
Registros disponibles: 5833
Variables disponibles: 17